import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBarDeskt, NavBarMobile } from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="md:fixed md:block top-0 left-0  h-full hidden z-50">
          <NavBarDeskt/>
        </div>
        <div className="md:ml-12 ml-0">{children}</div>

        <div className="md:hidden fixed bottom-0 left-0 w-full z-50">
          <NavBarMobile />
        </div>
      </body>
    </html>
  );
}
